name: Run MicroPython on STM32F103C8T6 with QEMU

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qemu-system-arm \
          arm-none-eabi-gcc \
          arm-none-eabi-binutils \
          arm-none-eabi-newlib \
          build-essential \
          git \
          python3 \
          python3-pip

    - name: Clone MicroPython repository
      run: git clone https://github.com/micropython/micropython.git --depth=1

    - name: Build MicroPython for STM32F103
      run: |
        cd micropython
        make -C mpy-cross
        cd ports/stm32
        make BOARD=NUCLEO_F103RB

    - name: Copy main.py to filesystem
      run: |
        mkdir -p qemu_fs
        cp lib/main.py qemu_fs/

    - name: Run with QEMU
      run: |
        cd micropython/ports/stm32
        qemu-system-arm \
          -machine stm32f103-board \
          -kernel build-NUCLEO_F103RB/firmware.bin \
          -nographic \
          -serial mon:stdio \
          -timeout-action shutdown \
          -timeout 30 || true